server:
  port: 8020
spring:
  application:   #定义服务名称
    name: consummer-user  #多个服务名称相同
eureka:
  client:
    service-url:
      #链接注册中心集群
       defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: consummer-user-8020                #定义微服务的名称 多个服务Id必须不同
    prefer-ip-address: true                        #是否显示IP和端口 

feign:
  hystrix:
    enabled: true                 #启动熔断器机制 !!!!!!!!!!!!!
